# Generated by Django 4.2.3 on 2023-07-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_day',
            field=models.IntegerField(default=1),
        ),
    ]
