# Generated by Django 4.2.3 on 2023-07-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputs_outputs',
            name='type',
            field=models.CharField(choices=[('I', 'Input'), ('O', 'Output')], max_length=1),
        ),
    ]
