# Generated by Django 4.2.3 on 2023-07-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bank', models.CharField(choices=[('NU', 'Nubank'), ('BB', 'Banco do Brasil'), ('CE', 'Caixa Economica'), ('IT', 'Itau'), ('SI', 'Sicredi')], max_length=2)),
                ('type', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Juridica')], max_length=2)),
                ('value', models.FloatField(default=0)),
                ('icone', models.ImageField(upload_to='icones')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('isEssencial', models.BooleanField(default=False)),
                ('intended_value', models.FloatField(default=0)),
            ],
        ),
    ]
