# Generated by Django 4.2.3 on 2023-07-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste', models.CharField(max_length=200)),
                ('teste_value', models.FloatField(default=0)),
            ],
        ),
    ]
