# Generated by Django 4.2.2 on 2023-07-06 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teste',
        ),
    ]
