# Generated by Django 4.2.2 on 2023-07-06 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_delete_teste'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='icone',
            new_name='icon',
        ),
    ]
