# Generated by Django 4.2.3 on 2023-07-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_rename_bill_account_rename_icone_account_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='intended_value',
            new_name='planning_value',
        ),
    ]
